//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_2025
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Books()
        {
            this.Reviews = new HashSet<Reviews>();
        }
    
        public int ID_books { get; set; }
        public string Name { get; set; }
        public int ID_authors { get; set; }
        public int ID_genre { get; set; }
        public int ID_languages { get; set; }
        public int ID_publishers { get; set; }
        public int ID_availability { get; set; }
        public int ID_categories { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public string Photo { get; set; }
        public Nullable<decimal> Costs { get; set; }
    
        public virtual Authors Authors { get; set; }
        public virtual Availability Availability { get; set; }
        public virtual ReaderCategories ReaderCategories { get; set; }
        public virtual Genres Genres { get; set; }
        public virtual Languages Languages { get; set; }
        public virtual Publishers Publishers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reviews> Reviews { get; set; }
    }
}
