//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_2025
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int ID_orders { get; set; }
        public int ID_books { get; set; }
        public int ID_users { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Result { get; set; }
        public int ID_orders_new { get; set; }
        public Nullable<int> NewColumn { get; set; }
    }
}
